///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DatiModel {
/*
{
  "question": "Which animal can change its color to match its surroundings? ",
  "a": "Chameleon",
  "b": "Ostrich",
  "answer": "a"
}
*/

  String? question;
  String? a;
  String? b;
  String? answer;

  DatiModel({
    this.question,
    this.a,
    this.b,
    this.answer,
  });
  DatiModel.fromJson(Map<String, dynamic> json) {
    question = json['question']?.toString();
    a = json['a']?.toString();
    b = json['b']?.toString();
    answer = json['answer']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['question'] = question;
    data['a'] = a;
    data['b'] = b;
    data['answer'] = answer;
    return data;
  }
}